# Generated by Django 5.2 on 2025-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_user_historicalemployee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_private',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='email_private',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
