# Generated by Django 5.2 on 2025-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_email_employee_private_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='personal_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
